name: Generic Template
description: It can be used for any issue since it contains the general requirements
labels: status-new,priority-medium
body:
  - type: markdown
    attributes:
      value: |
        Before opening an issue, please be sure that no one opened the same issue to avoid duplicates. 
        
        ---
        
        Thank you for using the issue template! Please don't forget to use it for the issues that you will create in the future too.
  - type: textarea
    id: issue-description
    attributes:
      value: |
      1.
      2.
      3.
      ...
      label: Issue Description
      description: "Please describe the issue with 2-3 clear sentences. What is this issue for, what's the aim of it? What you will do for this issue?"
    validations:
      required: true
  - type: input
    id: deadline
    attributes:
      label: Deadline of the Issue
      description: "Please provide a deadline for the issue."
      placeholder: "19.03.2022 - Saturday - 23:59"
    validations:
      required: true
  - type: dropdown
    id: reviewer
    attributes:
      label: Reviewer
      description: "Who will review this issue? Please select the reviewer from the list below."
      options:
        - Bahrican Yesil
        - Egemen Atik
        - Altay Acar
        - Ezgi Aysel Batı
        - Muhammed Enes Sürmeli
        - Onur Kömürcü
        - Mehmet Batuhan Çelik
        - Hasan Can Erol
        - Ahmet Yiğit Özdoğan
        - Ecenur Sezer
        - Someone Else
        - No Reviewer
    validations:
      required: true
  - type: input
    id: review-deadline
    attributes:
      label: Deadline for the Review
      description: "Please provide a deadline for the review process."
      placeholder: "19.03.2022 - Saturday - 23:59"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
