name: Generic Template
description: It can be used for any issue since it contains the general requirements
labels: status-new,priority-medium
body:
  - type: markdown
    attributes:
      value: |
        Before opening an issue, please be sure that no one opened the same issue to avoid duplicates. 
        
        ---
        
        Thank you for using the issue template! Please don't forget to use it for the issues that you will create in the future too.
  - type: textarea
    id: issue-description
    attributes:
      value: "I will be creating some issue templates to ensure unity among the team members and not miss some important steps that will make the issue description clearer. We have discussed this in our second and third meetings and decided that it will be helpful for the issue creators to directly fill the required sections without thinking about 'what is required'."
      label: Issue Description
      description: "Please describe the issue with 2-3 clear sentences. What is this issue for, what's the aim of it? What you will do for this issue?"
    validations:
      required: true
  - type: textarea
    id: step-details
    attributes:
      value: "It should have these subsections (can be expanded more in the future):\n\n1. Requirements:\n2. Questions About Requirements\n3. Similar Projects\n4. Base Features"
      label: Step Details
      description: "This is an optional field. What will be the steps/actions you will perform?"
  - type: input
    id: deadline
    attributes:
      label: Deadline of the Issue
      description: "Please provide a deadline for the issue."
      placeholder: "19.03.2022 - Saturday - 23:59"
    validations:
      required: true
  - type: dropdown
    id: reviewer
    attributes:
      label: Reviewer
      description: "Who will review this issue? Please select the reviewer from the list below."
      options:
        - Bahrican Yesil
        - Egemen Atik
        - Altay Acar
        - Ezgi Aysel Batı
        - Muhammed Enes Sürmeli
        - Onur Kömürcü
        - Mehmet Batuhan Çelik
        - Hasan Can Erol
        - Ahmet Yiğit Özdoğan
        - Ecenur Sezer
        - Someone Else
        - No Reviewer
    validations:
      required: true
  - type: input
    id: review-deadline
    attributes:
      label: Deadline for the Review
      description: "Please provide a deadline for the review process."
      placeholder: "19.03.2022 - Saturday - 23:59"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
